Repository Team-Qampus/Qampus_FE, pull requests merged in 2025-03, with the labels that each got.

#42 토큰 유무에 따른 헤더 아이콘 변경
  components/layout/Header.tsx
  public/svg/right-arrow-black.svg
  public/svg/right-arrow-white.svg
Labels: ✨ Feature

#45 CRUD 관련 사소한 오류 수정
  app/apis/logoutApi.ts
  app/mypage/_components/InfoCard.tsx
  app/userMain/page.tsx
  components/Answer.tsx
  components/PreviewCard.tsx
  components/ViewQuestion.tsx
  components/layout/Header.tsx
  type.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#46 커뮤니티 리팩토링
  app/apis/rankApi.ts
  app/community/[univId]/page.tsx
  app/community/_component/Info.tsx
  app/community/_component/UnivMap.tsx
  app/community/_component/UnivMapArea.tsx
  app/guestMain/_components/Page3/Sliders.tsx
  app/guestMain/_components/Page5/index.tsx
  app/userMain/_components/MoveButton.tsx
  app/userMain/_components/UserInfo.tsx
  app/userMain/page.tsx
  components/ranking/Slider.tsx
  hooks/.gitkeep
  hooks/useMapPosition.ts
  public/images/main/introduce1.png
  public/images/main/introduce2.png
  public/images/main/introduce3.png
  public/images/univ/102.png
  public/images/univ/105.png
  public/images/univ/106.png
  public/images/univ/107.png
  public/images/univ/108.png
  public/images/univ/2.png
  public/images/univ/252.png
  public/images/univ/253.png
  public/images/univ/52.png
  public/images/univ/53.png
  public/images/univ/55.png
  public/images/univ/56.png
  public/images/univ/57.png
  public/images/univ/59.png
  public/images/univ/999.png
  public/images/univ/9999.png
  public/images/univ/99999.png
  tailwind.config.ts
  type.ts
Labels: ✨ Feature, 🔨 Refactor

#51 답변 메인 페이지 등록 날짜 안 보이는 문제 수정
  app/answer/answerMain/page.tsx
  components/ViewQuestion.tsx
Labels: 🔨 Refactor

#53 로그아웃 로직 리팩토링
  app/community/[univId]/page.tsx
  app/community/_component/UnivMap.tsx
  app/global-error.tsx
  app/question/[questionId]/page.tsx
  components/ViewQuestion.tsx
  components/layout/Header.tsx
  middleware.ts
  public/images/characters/error.png
  public/images/univ/302.png
Labels: ✨ Feature, 🔨 Refactor

#55 질문 / 답변 / 검색페이지 3차 수정
  app/answer/answerMain/page.tsx
  app/apis/answerApi.ts
  app/apis/myPageApi.ts
  app/apis/questionApi.ts
  app/mypage/page.tsx
  app/question/questionCreate/page.tsx
  app/search/page.tsx
  components/Answer.tsx
  components/PreviewCard.tsx
  components/SortSelector.tsx
  components/ViewAnswer.tsx
  components/WriteAnswer.tsx
  components/WriteQuestion.tsx
  type.ts
Labels: ✨ Feature, 🔨 Refactor, 📬 API
